### ISSUE TITLE
Erro discovery

### ISSUE THREAD

**Issue by paulor1610** [romainsi/zabbix-BackupExec-jobs#1]
testing by zabbix_sender error

You cannot call a method on a null-valued expression.
At C:\.....\zabbix_sbr_job.ps1:28 char:1
+ $apptasksok =
$apptasksok1.replace('▒','&acirc;').replace('▒','&agrave;').replac ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

{
 "data":[


 ]
}

**Comment by romainsi** [comment]
Hi,

The problem would be that he doesn't find any backups.
Can you check by executing the following powershell commands :
Import-Module BEMCLI
Get-BEJob -Jobtype Backup -Status Active

And see if the script returns a value (see screenshot)
![answer](https://user-images.githubusercontent.com/30522413/32599705-9f51b392-c53d-11e7-8b95-c61545047719.png)

**Comment by paulor1610** [comment]
thank you, after the jos performed they appeared

**Comment by romainsi** [comment]
Ok. Cool ;)
