### ISSUE TITLE
Cannot update host

### ISSUE THREAD

**Issue by andrew2310** [romainsi/zabbix-BackupExec-jobs#2]
Hello,

I tried setting this up but at the final step of linking the template to the host I get this error:

Cannot update host

Item with key "service_state[BackupExecAgentBrowser]" already exists on "HOST_NAME" as an item created from item prototype.

Can you help, please?

**Comment by romainsi** [comment]
Hi,

Verify you have not an item with key : service_state in your host when you import.
Try to import to an other host for test.
