### ISSUE TITLE
LLD Symantec BackupExec Jobs - Not supported

### ISSUE THREAD

**Issue by LFPSGS** [romainsi/zabbix-BackupExec-jobs#3]
After a few minutes this lld item is the only one who became "Not Supported (Timeout while executing a shell script)"

I did have to enable script execution policy on powershell at the server (Set-ExecutionPolicy unrestricted).

BTW, iam using Zabbix 3.4.6 and Veritas BackupExec 16.

**Comment by romainsi** [comment]
Hi, 

I never trying with BackupExec 16 ...
In zabbix server can you try to launch this command and send me the result ? :

`zabbix_get -s "name or ip of your BE16 server' -k 'sbr["DiscoverTasks"]'`

**Comment by glutzm** [comment]
Hi,

I'm using Zabbix 4.2.2 and Veritas BackupExec 16 and the script works fine.

I also had problem with "timeout while executing a shell script" during some steps (both discovery and the discovered items itself).
I solved by increasing a bit of the timeout in both Zabbix Agent on the BackupExec host and Zabbix Server conf, and increased a bit of the agent pollers in Zabbix Server.
